- name: "[base] installing dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600 autoremove=yes
  with_items:
    - python
    - python-dev
    - python-mysqldb
    - python-pip
    - python-virtualenv
    - libevent-dev
    - libev-dev
    - libzmq3-dev
    - libxml2-dev
    - libxslt1-dev

- name: "uninstall postfix"
  apt: name={{ item }} state=absent
  with_items:
    - postfix

- name: rsync local codebase contents to the server
  synchronize: src="{{ local_repository_root_path }}/parrotmail/" dest="{{ parrotmail_install_dir }}/" recursive=yes perms=yes compress=yes
  notify:
    - restart parrotmail

- name: ensure mail folder
  file: path="{{ parrotmail_install_dir }}" state=directory

- name: ensure subdirs
  file: path="{{ item }}" state=directory mode=0775 owner="{{ parrotmail_user }}" group=www-data
  with_items:
    - "{{ parrotmail_inbox_dir }}"
    - "{{ parrotmail_install_dir }}"
    - "{{ parrotmail_venv_dir }}"

- name: fix owner permissions on subdirs
  file: path="{{ item }}" owner="{{ parrotmail_user }}" group="{{ parrotmail_user }}" recurse=yes mode=0755
  with_items:
    - "{{ parrotmail_inbox_dir }}"
    - "{{ parrotmail_install_dir }}"
    - "{{ parrotmail_venv_dir }}"

- name: install latest setuptools
  pip: name=setuptools state=latest
       virtualenv="{{ venv_path }}"

- name: install latest pip
  pip: name=pip state=latest
       virtualenv="{{ venv_path }}"

- name: install requirements
  pip: requirements="/srv/src/requirements.txt"
       virtualenv="{{ venv_path }}"

- name: install parrotmail upstart script
  template: src=parrotmail.upstart
    dest="/etc/init/parrotmail.conf"
    owner="{{ parrotmail_user }}" group="{{ parrotmail_user }}" mode=644
  notify: restart parrotmail

- name: test parrotmail upstart script
  shell: init-checkconf /etc/init/parrotmail.conf && initctl check-config parrotmail
  notify: restart parrotmail
