#!/bin/bash

# Generated by ansible

pushd "{{ backup_folder_path }}"
now="$(date +"%m-%d-%Y")"

export BACKUP_FILE="{{ backup_folder_path }}/log-files-${now}-backup.aes"
export TEMPTAR_FILE="{{ backup_folder_path }}/log-files-${now}-backup.tar.bz2"

sudo tar cjvf "${TEMPTAR_FILE}" "/var/log/{{ application_name }}/*"
sudo openssl aes-256-cbc -a -salt -in "${TEMPTAR_FILE}" -out "${BACKUP_FILE}" -pass "file:{{ encryption_key_path }}"
rm -fv "${TEMPTAR_FILE}"
