---
# =====================================================
#
#                        ,d
#                        88
# ,adPPYba,  ,adPPYba, MM88MMM 88       88 8b,dPPYba,
# I8[    "" a8P_____88   88    88       88 88P'    "8a
#  `"Y8ba,  8PP"""""""   88    88       88 88       d8
# aa    ]8I "8b,   ,aa   88,   "8a,   ,a88 88b,   ,a8"
# `"YbbdP"'  `"Ybbd8"'   "Y888  `"YbbdP'Y8 88`YbbdP"'
#                                          88
#                                          88
#
# .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..

# - name: rotate logs
#   shell: logrotate -f /etc/logrotate.conf
#   ignore_errors: true

# - name: remove compressed log backups [DANGER]
#   shell: find /var/log -name '*.gz' -exec rm -fv {} \;
#   ignore_errors: true
