---
# ========================================================
#
# ,adPPYba, 8b       d8 ,adPPYba,
# I8[    "" `8b     d8' I8[    ""
#  `"Y8ba,   `8b   d8'   `"Y8ba,
# aa    ]8I   `8b,d8'   aa    ]8I
# `"YbbdP"'     Y88'    `"YbbdP"'
#               d8'
#              d8'
#
#                     88                    88
#                     88                    ""
#                     88
# ,adPPYYba,  ,adPPYb,88 88,dPYba,,adPYba,  88 8b,dPPYba,
# ""     `Y8 a8"    `Y88 88P'   "88"    "8a 88 88P'   `"8a
# ,adPPPPP88 8b       88 88      88      88 88 88       88
# 88,    ,88 "8a,   ,d88 88      88      88 88 88       88
# `"8bbdP"Y8  `"8bbdP"Y8 88      88      88 88 88       88
#
#
#                                88
#   ,d                           88
#   88                           88
# MM88MMM ,adPPYba,   ,adPPYba,  88 ,adPPYba,
#   88   a8"     "8a a8"     "8a 88 I8[    ""
#   88   8b       d8 8b       d8 88  `"Y8ba,
#   88,  "8a,   ,a8" "8a,   ,a8" 88 aa    ]8I
#   "Y888 `"YbbdP"'   `"YbbdP"'  88 `"YbbdP"'
# .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..


- name: "[sysadmin tools] bellyfeel environment bash lib"
  template:
    src: "env.sh.j2"
    dest: "{{ bellyfeel_tools_dir }}/env.sh"
    owner: root
    group: root
    mode: 644
