---
- hosts:
    - bellyfeel.io

  user: root

  # vars:
  #   # force drop the mysql database
  #   bellyfeel_mysql_force_drop_db: yes

  vars_files:
    - "bellyfeel-vault.yml"

  tasks:
    - debug: var=ansible_all_ipv4_addresses

  roles:
    # automatic mount droplet volumes and update fstab
    # - digitalocean

    - base/enable-standard-cronjobs
    - base/system-updates
    - base/ulimit

    - security/system-hardening
    - security/firewall

    - servers/nginx
    - servers/mysql-db
    - servers/redis
    - servers/memcached
    - servers/onion

    - apps/ssl
    - apps/web
